In [2]:
import pandas as pd
import numpy as np

# Load the raw dataset
url = "https://raw.githubusercontent.com/plotly/datasets/master/supermarket_Sales.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

df.head()

Dataset loaded successfully!
Dataset shape: (1000, 17)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Cost of goods sold,Gross margin percentage,Gross income,Customer stratification rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [3]:
# Display column names
print("Column names:")
print(df.columns.tolist())

# Check data types and missing values
print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

Column names:
['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date', 'Time', 'Payment', 'Cost of goods sold', 'Gross margin percentage', 'Gross income', 'Customer stratification rating']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Invoice ID                      1000 non-null   object
 1   Branch                          1000 non-null   object
 2   City                            1000 non-null   object
 3   Customer type                   1000 non-null   object
 4   Gender                          1000 non-null   object
 5   Product line                    1000 non-null   object
 6   Unit price                      1000 non-null   float64
 7   Quantity                        1000 non-null   int64
 8   Tax 5%                          1000 non-null   float64
 9   Total                           1000 non-null   float64
 10  Date                            1000 non-null   object
 11  Time                            1000 non-null   object
 12  Payment                         1000 non-null   object
 13  Cost of goods sold              1000 non-null   float64
 14  Gross margin percentage         1000 non-null   float64
 15  Gross income                    1000 non-null   float64
 16  Customer stratification rating  1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

Missing values:
Invoice ID                        0
Branch                            0
City                              0
Customer type                     0
Gender                            0
Product line                      0
Unit price                        0
Quantity                          0
Tax 5%                            0
Total                             0
Date                              0
Time                              0
Payment                           0
Cost of goods sold                0
Gross margin percentage           0
Gross income                      0
Customer stratification rating    0
dtype: int64

Duplicate rows: 0

In [4]:
def clean_data(data):
    # Create a copy to protect the original dataset

    data = data.copy()

    # Remove extra spaces from column names
    data.columns = data.columns.str.strip()

    # Remove duplicate rows
    data = data.drop_duplicates()

    # Remove rows containing missing values
    data = data.dropna()

    return data


# Clean the dataset
df_clean = clean_data(df)

print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_clean.shape)

df_clean.head()

Original dataset shape: (1000, 17)
Cleaned dataset shape: (1000, 17)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,Cost of goods sold,Gross margin percentage,Gross income,Customer stratification rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [5]:
def process_data(data):
    # Convert the Total column into a NumPy array
    sales = data["Total"].to_numpy(dtype=float)

    # Calculate statistics using NumPy
    results = {
        "Total Sales": np.sum(sales),
        "Average Sales": np.mean(sales),
        "Maximum Sale": np.max(sales),
        "Minimum Sale": np.min(sales),
        "Standard Deviation": np.std(sales)
    }

    return results


# Process the cleaned dataset
results = process_data(df_clean)

print("Data Processing Results:")
for key, value in results.items():
    print(f"{key}: {value:.2f}")

Data Processing Results:
Total Sales: 322966.75
Average Sales: 322.97
Maximum Sale: 1042.65
Minimum Sale: 10.68
Standard Deviation: 245.76

In [6]:
# Calculate total sales for each product line
sales_by_product = df_clean.groupby("Product line")["Total"].sum()

print("Total Sales by Product Line:")
print(sales_by_product.sort_values(ascending=False))

Total Sales by Product Line:
Product line
Food and beverages        56144.8440
Sports and travel         55122.8265
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Home and lifestyle        53861.9130
Health and beauty         49193.7390
Name: Total, dtype: float64

In [7]:
# Save the cleaned dataset
output_file = "cleaned_supermarket_sales.csv"

df_clean.to_csv(output_file, index=False)

print("Cleaned dataset exported successfully:", output_file)

Cleaned dataset exported successfully: cleaned_supermarket_sales.csv

In [8]:
from google.colab import files

files.download("cleaned_supermarket_sales.csv")

In [9]:
%%writefile requirements.txt
numpy
pandas
matplotlib
jupyter

Writing requirements.txt

In [10]:
from google.colab import files

files.download("requirements.txt")